### ISSUE TITLE
Good project, would you offer a bower || npm repository?

### ISSUE THREAD

**Issue by faller** [vvllaadd/filerun.js#1]
I like it rather than https://github.com/flowjs/flow.js or https://github.com/23/resumable.js

**Comment by faller** [comment]
How do I set it up with my server? Would you write some documents for it ?
I'm writing a project for adapting GridFS and S3. It's better saving chunks to a shared storage in a cluster environment. GridFS has chunk api so we don't have to do a merge operation.

**Comment by vvllaadd** [comment]
>would you offer a bower || npm repository?
If anybody else would like to contribute with that, fine. Me, I am not interested in it.

>How do I set it up with my server?
The example should be easy to follow. If it is not, consider contacting an experienced web developer.

>GridFS and S3
I have no interest in adapting the library to such systems, sorry.
